### ISSUE TITLE
Invalid XRP balance 

### ISSUE THREAD

**Issue by gemcoder21** [gemwalletcom/gem-android#105]
![IMAGE 2024-12-15 3:40:00 PM](https://github.com/user-attachments/assets/cd00a131-3b0b-4d5e-868a-d4be0812899c)
![IMAGE 2024-12-15 3:40:03 PM](https://github.com/user-attachments/assets/f3016329-1302-47d6-8fa3-f4cca5ba680f)
![IMAGE 2024-12-15 3:40:06 PM](https://github.com/user-attachments/assets/6b2f9e07-1c63-4e7f-86d5-d6ea92469ae8)

**Comment by gemcoder21** [comment]
Address: rwCq6DCHa6HPFyfvabvzcX1y5wABw5KdiN

**Comment by furenster** [comment]
Fixed https://github.com/gemwalletcom/gem-android/commit/45f359e46105db6d8137b49285ce6c9c28a7fa37
