### ISSUE TITLE
Fix Smartchain balance issue

### ISSUE THREAD

**Issue by gemcoder21** [gemwalletcom/gem-android#51]
Based on https://github.com/gemwalletcom/gem-ios/commit/147dd857036ae3f651de3d673fca6d1971f07321

If you have BNB staking in awaitingWithdrawal state, it should show in the staking balance.

**Comment by furenster** [comment]
https://github.com/gemwalletcom/gem-android/commit/0dfca28eea7869349d8f42c2e17ca5eba04261a0
